In [ ]:
%pip install pandas

In [2]:
import numpy as np
import pandas as pd

## Pandas Series

A series is a one dimensional labelled array capable of holding any data type. the axis labels are collectively called the index .

## Creating series

In [3]:
labels =[ 'a' ,'b','c']
my_list = [10,20,30]
my_arr =np.array([10,20,30])
my_dict = {"a":10,"b":20,"c":30}
pd.Series(my_list ,index=labels)
pd.Series(my_dict)

a    10
b    20
c    30
dtype: int64

## Data Frame

In [4]:
people_dict = {
    "name": ["Sandesh", "Aarav", "Priya", "Rohan"],
    "age": [24, 28, 26, 30],
    "city": ["Pokhara", "Kathmandu", "Lalitpur", "Biratnagar"],
    "salary": [65000, 80000, 72000, 90000]
}
df1 =pd.DataFrame(people_dict)

In [5]:
people_list = [
    ["Sandesh", 24, "Pokhara", 65000],
    ["Aarav", 28, "Kathmandu", 80000],
    ["Priya", 26, "Lalitpur", 72000],
    ["Rohan", 30, "Biratnagar", 90000]
]
columns= ["name" ,"age" ,"city" ,"salary"]
df2 =pd.DataFrame(people_list , columns=columns)

In [6]:
df1[["name","salary"]]

      name  salary
0  Sandesh   65000
1    Aarav   80000
2    Priya   72000
3    Rohan   90000

In [7]:
df1["profession"] =["chill" ,"doctor","pilot","teacher"]

In [8]:
df1

      name  age        city  salary profession
0  Sandesh   24     Pokhara   65000      chill
1    Aarav   28   Kathmandu   80000     doctor
2    Priya   26    Lalitpur   72000      pilot
3    Rohan   30  Biratnagar   90000    teacher

In [12]:
df1

      name  age        city  salary
0  Sandesh   24     Pokhara   65000
1    Aarav   28   Kathmandu   80000
2    Priya   26    Lalitpur   72000
3    Rohan   30  Biratnagar   90000

## Selecting only certain portion of data

In [13]:
df1.loc[0]

name      Sandesh
age            24
city      Pokhara
salary      65000
Name: 0, dtype: object

In [15]:
df1.loc[[0,1]][["city","salary"]]

        city  salary
0    Pokhara   65000
1  Kathmandu   80000

In [17]:
df1.loc[[2,3]][["name","age"]]

    name  age
2  Priya   26
3  Rohan   30

## Conditional Selection

In [20]:
# people with age over 25
df2[(df2["age"]>25 )& (df2["city"] == "Kathmandu")]

    name  age       city  salary
1  Aarav   28  Kathmandu   80000