In [1]:
import pandas as pd 
import numpy as np

## Finding Missing Data

In [2]:
data = {
    "A": [1, 2, np.nan, 4, 5],
    "B": [np.nan, 2, 3, 4, 5],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [1, np.nan, np.nan, np.nan, 5],
}
df1 =pd.DataFrame(data)
print(df1)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [3]:
df1.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df1.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [5]:
df1.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing data

In [6]:
df1.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

## Filling missing value

In [7]:
df1.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [8]:
values ={"A":5 ,"B":10,"C":100,"D":400}
df1.fillna(value=values)

     A     B      C      D
0  1.0  10.0    1.0    1.0
1  2.0   2.0    2.0  400.0
2  5.0   3.0    3.0  400.0
3  4.0   4.0  100.0  400.0
4  5.0   5.0  100.0    5.0

In [9]:
df1.fillna(df1.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

## Merging joining and concatination

In [20]:
## Merging two data frames

employee_info = {
    "employee_id": [101, 102, 103, 104, 105],
    "name": ["Sandesh", "Aarav", "Priya", "Rohan", "Sita"],
    "department": ["Engineering", "HR", "Finance", "Marketing", "Sales"]
}

employee_compensation = {
    "employee_id": [101, 102, 103, 106, 107],
    "salary": [75000, 60000, 68000, 72000, 65000],
    "bonus": [5000, 3000, 4500, 4000, 3500]
}

df_info = pd.DataFrame(employee_info)
df_compensation = pd.DataFrame(employee_compensation)
pd.merge(df_info,df_compensation ,on="employee_id", how="inner")

   employee_id     name   department  salary  bonus
0          101  Sandesh  Engineering   75000   5000
1          102    Aarav           HR   60000   3000
2          103    Priya      Finance   68000   4500

In [21]:
pd.merge(df_info,df_compensation ,on="employee_id", how="outer")

   employee_id     name   department   salary   bonus
0          101  Sandesh  Engineering  75000.0  5000.0
1          102    Aarav           HR  60000.0  3000.0
2          103    Priya      Finance  68000.0  4500.0
3          104    Rohan    Marketing      NaN     NaN
4          105     Sita        Sales      NaN     NaN
5          106      NaN          NaN  72000.0  4000.0
6          107      NaN          NaN  65000.0  3500.0

In [22]:
pd.merge(df_info,df_compensation ,on="employee_id", how="left")

   employee_id     name   department   salary   bonus
0          101  Sandesh  Engineering  75000.0  5000.0
1          102    Aarav           HR  60000.0  3000.0
2          103    Priya      Finance  68000.0  4500.0
3          104    Rohan    Marketing      NaN     NaN
4          105     Sita        Sales      NaN     NaN

In [23]:
pd.merge(df_info,df_compensation ,on="employee_id", how="right")

   employee_id     name   department  salary  bonus
0          101  Sandesh  Engineering   75000   5000
1          102    Aarav           HR   60000   3000
2          103    Priya      Finance   68000   4500
3          106      NaN          NaN   72000   4000
4          107      NaN          NaN   65000   3500